=== hbz/lobid-resources/src/test/resources/schemas/resource.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "lobid-resources",
  "description": "This is a generic JSON schema for validating a JSON document against the lobid-resources data model",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "@context": {
      "$ref": "context.json"
    },
    "id": {
      "$ref": "id.json"
    },
    "type": {
      "$ref": "type.json"
    },
    "abstract": {
      "title": "Abstract",
      "type": "array"
    },
    "accessRights": {
      "$ref": "accessRights.json"
    },
    "almaMmsId": {
      "title": "ALMA MMS identifier",
      "type": "string",
      "pattern": "\\d{17}"
    },
    "alternateGraphicRepresentation": {
      "$ref": "alternateGraphicRepresentation.json"
    },
    "alternativeTitle": {
      "title": "Variations of the title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b3KatId": {
      "title": "B3Kat identifier",
      "type": "string"
    },
    "bibliographicCitation": {
      "type": "string"
    },
    "bibliographicLevel": {
      "$ref": "bibliographicLevel.json"
    },
    "conditionsOfAccess": {
      "$ref": "conditionsOfAccess.json"
    },
    "containedIn": {
      "$ref": "containedIn.json"
    },
    "containsExampleOfWork": {
      "$ref": "containsExampleOfWork.json"
    },
    "contribution": {
      "$ref": "contribution.json"
    },
    "describedBy": {
      "$ref": "describedBy.json"
    },
    "deprecatedUri": {
      "$ref": "id.json"
    },
    "description": {
      "$ref": "description.json"
    },
    "disambiguatingDescription": {
      "title": "Dynamic helper element for deduplicating efforts.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dnbId": {
      "title": "DNB identifier",
      "type": "string"
    },
    "doi": {
      "$ref": "doi.json"
    },
    "edition": {
      "title": "Statement on the edition of the resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exampleOfWork": {
      "$ref": "exampleOfWork.json"
    },
    "extent": {
      "title": "Extent",
      "type": "string"
    },
    "fulltextOnline": {
      "$ref": "fulltextOnline.json"
    },
    "hasItem": {
      "$ref": "hasItem.json"
    },
    "hbzId": {
      "title": "hbz identifier",
      "type": "string"
    },
    "hebisId": {
      "title": "hebis PPN identifier",
      "type": "string"
    },
    "inCollection": {
      "$ref": "inCollection.json"
    },
    "isPartOf": {
      "$ref": "isPartOf.json"
    },
    "isbn": {
      "$ref": "isbn.json"
    },
    "issn": {
      "$ref": "issn.json"
    },
    "ismn": {
      "$ref": "ismn.json"
    },
    "k10PlusId": {
      "title": "K10Plus identifier",
      "type": "string"
    },
    "langNote": {
      "title": "Note concerning the language of a resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "language": {
      "$ref": "language.json"
    },
    "license": {
      "$ref": "license.json"
    },
    "manufacture": {
      "$ref": "manufacture.json"
    },
    "medium": {
      "$ref": "medium.json"
    },
    "natureOfContent": {
      "$ref": "natureOfContent.json"
    },
    "note": {
      "$ref": "note.json"
    },
    "oclcNumber": {
      "title": "OCLC number",
      "description": "The OCLC number of the resource",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "\\d{1,14}"
      }
    },
    "otherTitleInformation": {
      "title": "Additional title information",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "predecessor": {
      "$ref": "predecessor.json"
    },
    "primaryForm": {
      "$ref": "primaryForm.json"
    },
    "publication": {
      "$ref": "publication.json"
    },
    "related": {
      "$ref": "related.json"
    },
    "responsibilityStatement": {
      "title": "Responsibility Statement",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rpbId": {
      "title": "RPB identifier",
      "type": "string"
    },
    "sameAs": {
      "$ref": "sameAs.json"
    },
    "secondaryForm": {
      "$ref": "secondaryForm.json"
    },
    "seeAlso": {
      "$ref": "seeAlso.json"
    },
    "shortTitle": {
      "title": "Short version of title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "spatial": {
      "$ref": "spatial.json"
    },
    "stockNumber": {
      "title": "Product identifier from retail or publisher",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subject": {
      "title": "Subject",
      "description": "Subject indexing of the resource",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "complexSubject.json"
          },
          {
            "$ref": "skosConcept.json"
          }
        ]
      }
    },
    "subjectAltLabel": {
      "title": "Alternative labels for subjects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subjectslabels": {
      "title": "Labels for all subjects needed by Digibib",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "successor": {
      "$ref": "successor.json"
    },
    "supplement": {
      "$ref": "supplement.json"
    },
    "tableOfContents": {
      "$ref": "tableOfContents.json"
    },
    "thesisInformation": {
      "title": "Information specific to the doctoral thesis",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "title": {
      "title": "Title",
      "type": "string"
    },
    "titleKeyword": {
      "title": "Keywords taken from the title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "urn": {
      "title": "urn",
      "description": "urn of the resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "webPageArchived": {
      "$ref": "webPageArchived.json"
    },
    "zdbId": {
      "title": "ZDB identifier",
      "type": "string",
      "pattern": "\\d{1,7}-[Xx\\d]"
    }
  },
  "required": [
    "@context",
    "id",
    "type"
  ]
}

=== hbz/lobid-resources/src/test/resources/timeCapsuleAlephData/TT002494857_aleph.json
{
  "type" : [ "Book", "Image", "BibliographicResource" ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/118521314",
      "type" : [ "Person" ],
      "label" : "Çoban, Ismail",
      "dateOfBirth" : "1945",
      "gndIdentifier" : "118521314"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ill",
      "label" : "Illustration"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/5150278-1",
      "type" : [ "CorporateBody" ],
      "label" : "Bergkamen. Kulturverwaltung",
      "altLabel" : "Kulturverwaltung. Bergkamen",
      "gndIdentifier" : "5150278-1"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ctb",
      "label" : "Beitragende/r"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/2052102-9",
      "type" : [ "CorporateBody" ],
      "label" : "Städtische Galerie Sohle 1 (Bergkamen). Kulturverwaltung",
      "altLabel" : [ "Sohle Eins, Multimedia-Galerie", "Städtische Galerie Sohle 1", "Stadtmuseum Bergkamen. Bildergalerie", "Stadtmuseum Bergkamen. Sohle 1, Kommunale Galerie", "Stadtmuseum Bergkamen. Sohle 1, Multimedia-Galerie", "Sohle Eins, Multimedia-Galerie. Bergkamen", "Sohle 1, Kommunale Galerie", "Kommunale Galerie Sohle 1", "Stadtmuseum Bergkamen. Kommunale Galerie", "Sohle Eins, Kommunale Galerie. Bergkamen", "Multimedia-Galerie. Bergkamen", "Sohle 1, Kommunale Galerie. Bergkamen", "Sohle Eins, Kommunale Galerie", "Kommunale Galerie. Bergkamen", "Stadtmuseum Bergkamen. Multimedia-Galerie", "Stadtmuseum Bergkamen. Galerie Sohle 1", "Bildergalerie der Stadt Bergkamen", "Stadtmuseum Bergkamen. Städtische Galerie Sohle 1", "Galerie Sohle 1. Bergkamen", "Bildergalerie Bergkamen" ],
      "gndIdentifier" : "2052102-9"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ctb",
      "label" : "Beitragende/r"
    }
  } ],
  "extent" : "53 BL. MIT ZAHLR. ABB. U. TAF., TEILS FARB.",
  "hasItem" : [ {
    "id" : "http://lobid.org/items/TT002494857:DE-Kn3:KMB%2FK%20COBAN,%207%20%201980#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-Kn3#!",
      "label" : "lobid Organisation"
    },
    "note" : [ "00020050" ],
    "callNumber" : "KMB/K COBAN, 7  1980",
    "label" : "KMB/K COBAN, 7  1980"
  }, {
    "id" : "http://lobid.org/items/TT002494857:DE-6-015:N%20C%20228#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-6-015#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "N C 228",
    "label" : "N C 228"
  } ],
  "note" : [ "NE: SOHLE 1 <GALERIE, BERGKAMEN>. - AUSSTELLUNGSKAT." ],
  "medium" : [ {
    "id" : "http://purl.org/lobid/lv#Miscellaneous",
    "label" : "Sonstiges"
  } ],
  "title" : "MALEREI, RADIERUNGEN, HOLZSCHNITTE",
  "hbzId" : "TT002494857",
  "oclcNumber" : [ "1075948907" ],
  "publication" : [ {
    "type" : [ "PublicationEvent" ],
    "location" : "DÜSSELDORF",
    "publishedBy" : "INTERNA-ORB",
    "startDate" : "1980"
  } ],
  "sameAs" : [ {
    "id" : "http://worldcat.org/oclc/1075948907",
    "label" : "1075948907"
  }, {
    "id" : "http://hub.culturegraph.org/resource/HBZ-TT002494857",
    "label" : "Culturegraph Ressource"
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/TT002494857",
    "type" : [ "BibliographicDescription" ],
    "dateCreated" : "20080718",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "2023-04-16T05:16:32",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/TT002494857",
        "type" : [ "DataFeedItem" ],
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "label" : "hbz-Ressource TT002494857 im Exportformat MAB2-XML"
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "provider" : {
      "id" : "http://lobid.org/organisations/DE-Kn3#!",
      "label" : "lobid Organisation"
    },
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-Kn3#!",
      "label" : "lobid Organisation"
    },
    "label" : "Webseite der hbz-Ressource TT002494857"
  },
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/TT002494857#!"
}

=== hbz/lobid-resources/src/test/resources/timeCapsuleAlephData/HT016791198_aleph.json
{
  "type" : [ "Book", "BibliographicResource" ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/119134764",
      "type" : [ "Person" ],
      "label" : "Gerz, Alfons",
      "dateOfBirth" : "1913",
      "dateOfDeath" : "1995",
      "gndIdentifier" : "119134764"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ctb",
      "label" : "Beitragende/r"
    }
  } ],
  "extent" : "312 S. : überw. Ill.",
  "hasItem" : [ {
    "id" : "http://lobid.org/items/HT016791198:DE-Kn41:2012%2F1#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-Kn41#!",
      "label" : "lobid Organisation"
    },
    "note" : [ "M" ],
    "callNumber" : "2012/1",
    "label" : "2012/1"
  }, {
    "id" : "http://lobid.org/items/HT016791198:DE-Kn41:49618#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-Kn41#!",
      "label" : "lobid Organisation"
    },
    "note" : [ "M" ],
    "callNumber" : "49618",
    "label" : "49618"
  } ],
  "responsibilityStatement" : [ "Gesamtverantwortung: Alfons Gerz ..." ],
  "language" : [ {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/fra",
    "label" : "Französisch"
  }, {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/ita",
    "label" : "Italienisch"
  }, {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/eng",
    "label" : "Englisch"
  } ],
  "medium" : [ {
    "id" : "http://rdaregistry.info/termList/RDAproductionMethod/1010",
    "label" : "Print"
  } ],
  "title" : "Leichtathletik, Segeln, Radsport, Ski",
  "hbzId" : "HT016791198",
  "isPartOf" : [ {
    "type" : [ "IsPartOfRelation" ],
    "hasSuperordinate" : [ {
      "id" : "http://lobid.org/resources/HT003422154#!",
      "label" : "Sport Gala"
    } ],
    "numbering" : "87"
  } ],
  "oclcNumber" : [ "1074729477" ],
  "publication" : [ {
    "type" : [ "PublicationEvent" ],
    "location" : "München",
    "publishedBy" : "ProSport Verl.",
    "startDate" : "1987"
  } ],
  "sameAs" : [ {
    "id" : "http://worldcat.org/oclc/1074729477",
    "label" : "1074729477"
  }, {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT016791198",
    "label" : "Culturegraph Ressource"
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/HT016791198",
    "type" : [ "BibliographicDescription" ],
    "modifiedBy" : {
      "id" : "http://lobid.org/organisations/DE-Kn41#!",
      "label" : "lobid Organisation"
    },
    "dateCreated" : "20110425",
    "dateModified" : "20120119",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "2023-04-16T02:21:54",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/HT016791198",
        "type" : [ "DataFeedItem" ],
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "label" : "hbz-Ressource HT016791198 im Exportformat MAB2-XML"
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-Kn41#!",
      "label" : "lobid Organisation"
    },
    "label" : "Webseite der hbz-Ressource HT016791198"
  },
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/HT016791198#!"
}

=== hbz/lobid-resources/src/test/resources/output/json/00733/HT007331917.json
{
  "@context" : "http://lobid.org/resources/context.jsonld",
  "contribution" : [ {
    "agent" : {
      "altLabel" : [ "Hülshoff, Anna Elisabeth von Droste-", "Deluosite-Xuersihuofu, ...", "Droste-Hülshoff, Anna Elisabeth von", "דרוסטה-הילסהוף, אנטה פון", "Droste-Hülshoff, Anette v.", "Droste-Hülshoff, Annette", "Droste-Hülshoff, Annette Elisabeth, Freiin von", "Von Droste-Hülshoff, Annette Elise", "Hülshoff, Annette von Droste", "Droste zu Hülshoff, Annette von", "Xuersihuofu, ... Deluosite-", "Droste, Annette", "Hülshoff, ... Droste-", "Hülshof, Annette von Droste-", "Droste-Hülshof, Annette von", "Hülshoff, Anette v. Droste-", "Droste-Hülshof, Annette, Freiin von", "Hülshoff, Anna Elisabeth Franziska Adolphine Wilhelmine Louise Maria von Droste zu", "Hülshoff, Anette von Droste-", "Droste-Hülshoff, A. von", "Droste-Hülshoff, Annette E. von", "Droste-Hülshoff, Anette von", "Droste zu Hülshoff, Elisabeth Anna", "Hülshoff, Anna Elisabeth v. Droste-", "Droste, ...", "Hülshoff, Annette von Droste-", "드로스테-휠스호프, 아네테 폰", "Hülshoff, Elisabeth Anna Droste zu", "Hülshoff, Annette Elisabeth Freiin von Droste-", "Droste-Huelshoff, Annette Elise von", "Hülshoff, A. von Droste-", "Droste Hülshoff, Annette von", "Droste-Hülshoff, ...", "Droste zu Hülshoff, Anna Elisabeth", "Droste-Huelshoff, Annette von", "Hülshoff, Anna Elisabeth Droste zu", "Von Droste-Hülshoff, Annette", "Droste zu Hülshoff, Anna Elisabeth Franziska Adolphine Wilhelmine Louise Maria von", "D.-H., Annette Elisabeth v.", "Hülshoff, Annette v. Droste-", "Droste zu Hülshoff, Anna Elisabeth Franzisca Adolphina Wilhelmina Ludovica", "Droste zu Hülshoff, Anna Elisabeth Francisca Maria Adolphina Wilhelmina Ludovica von", "Droste, Annette von", "Droste-Hülshoff, Anna Elisabeth v.", "Hyurusuhofu, ... Dorosute-", "Von Droste-Hülshoff, Anna Elisabeth", "Hülshoff, Annette von Droste zu", "Huelshoff, Annette von Droste-", "Droste-Hülshoff, Annette Freiin von", "Droste-Hülshoff, Annette v." ],
      "dateOfBirth" : "1797",
      "dateOfDeath" : "1848",
      "id" : "http://d-nb.info/gnd/118527533",
      "label" : "Droste-Hülshoff, Annette von",
      "type" : [ "Person" ]
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/cre",
      "label" : "Autor/in"
    },
    "type" : [ "Contribution" ]
  }, {
    "agent" : {
      "altLabel" : [ "Hirsch, Karl Georg", "Hirsch, Karl-Georg (Künstler)" ],
      "dateOfBirth" : "1938",
      "gndIdentifier" : "118705172",
      "id" : "http://d-nb.info/gnd/118705172",
      "label" : "Hirsch, Karl-Georg",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "Person" ]
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ill",
      "label" : "Illustration"
    },
    "type" : [ "Contribution" ]
  } ],
  "describedBy" : {
    "dateCreated" : "19970502",
    "id" : "http://lobid.org/resources/HT007331917",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "label" : "Webseite der hbz-Ressource HT007331917",
    "resultOf" : {
      "endTime" : "0001-01-01T00:00:00",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "label" : "Software lobid-resources",
        "type" : [ "SoftwareApplication" ]
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/HT007331917",
        "isPartOf" : [ {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "https://datahub.io/dataset"
        } ],
        "label" : "hbz-Ressource HT007331917 im Exportformat MAB2-XML",
        "type" : [ "DataFeedItem" ]
      },
      "type" : [ "CreateAction" ]
    },
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-836#!",
      "label" : "lobid Organisation"
    },
    "type" : [ "BibliographicDescription" ]
  },
  "extent" : "89 S. : Ill.",
  "hasItem" : [ {
    "callNumber" : "AQSH 1",
    "describedBy" : {
      "id" : "http://lobid.org/items/HT007331917:DE-836:AQSH%201",
      "label" : "lobid Bestandsressource"
    },
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-836",
      "label" : "lobid Organisation"
    },
    "id" : "http://lobid.org/items/HT007331917:DE-836:AQSH%201#!",
    "itemOf" : {
      "id" : "http://lobid.org/resources/HT007331917#!",
      "label" : "lobid Ressource"
    },
    "label" : "AQSH 1",
    "note" : "00007007",
    "type" : [ "Item" ]
  } ],
  "hbzId" : "HT007331917",
  "id" : "http://lobid.org/resources/HT007331917#!",
  "isbn" : [ "9783922406662", "3922406661" ],
  "medium" : [ {
    "id" : "http://rdaregistry.info/termList/RDAproductionMethod/1010",
    "label" : "Print"
  } ],
  "publication" : [ {
    "location" : "Memmingen",
    "publishedBy" : "Visel",
    "startDate" : "1996",
    "type" : [ "PublicationEvent" ]
  } ],
  "responsibilityStatement" : [ "Annette von Droste-Hülshoff. Holzstiche von Karl-Georg Hirsch" ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT007331917",
    "label" : "Culturegraph Ressource"
  } ],
  "subject" : [ {
    "componentList" : [ {
      "altLabel" : [ "Hirsch, Karl Georg", "Hirsch, Karl-Georg (Künstler)" ],
      "dateOfBirth" : "1938",
      "gndIdentifier" : "118705172",
      "id" : "http://d-nb.info/gnd/118705172",
      "label" : "Hirsch, Karl-Georg",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "Person" ]
    }, {
      "gndIdentifier" : "4123412-1",
      "id" : "http://d-nb.info/gnd/4123412-1",
      "label" : "Illustration",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "SubjectHeading" ]
    }, {
      "gndIdentifier" : "4125166-0",
      "id" : "http://d-nb.info/gnd/4125166-0",
      "label" : "Holzstich",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "SubjectHeading" ]
    }, {
      "gndIdentifier" : "4113356-0",
      "id" : "http://d-nb.info/gnd/4113356-0",
      "label" : "Droste-Hülshoff, Annette von: Die Judenbuche",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "Work" ]
    } ],
    "label" : "Hirsch, Karl-Georg | Illustration | Holzstich | Droste-Hülshoff, Annette von: Die Judenbuche  ",
    "type" : [ "ComplexSubject" ]
  }, {
    "componentList" : [ {
      "gndIdentifier" : "123456789",
      "id" : "http://d-nb.info/gnd/123456789",
      "label" : "Mustermann, Max: Werk XY",
      "source" : {
        "id" : "http://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "type" : [ "Work" ]
    } ],
    "label" : "Mustermann, Max: Werk XY",
    "type" : [ "ComplexSubject" ]
  } ],
  "subjectAltLabel" : [ "Buchillustrationen", "Buch / Illustration", "Buchillustration", "Hirsch, Karl Georg (1938-)", "Wissenschaftliche Illustration", "Bildmaterial (Buchkunst)", "Tonstich", "Xylographie", "Holzstiche", "Xylografie", "Illustrationen", "Abbildung (Buchkunst)", "Bebilderung", "Hirsch, Karl-Georg (Künstler) (1938-)" ],
  "title" : "Die Judenbuche",
  "type" : [ "BibliographicResource", "Book" ]
}

=== hbz/lobid-resources/src/test/resources/timeCapsuleAlephData/HT010662586_aleph.json
{
  "type" : [ "Book", "BibliographicResource" ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/118839055",
      "type" : [ "Person" ],
      "label" : "Wedgwood, Cicely V.",
      "altLabel" : [ "Wedgwood, Veronica", "Wedgwood, Cicely Veronica", "Wedgwood, C. V." ],
      "dateOfBirth" : "1910",
      "dateOfDeath" : "1997",
      "gndIdentifier" : "118839055"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    }
  } ],
  "extent" : "23 p.",
  "responsibilityStatement" : [ "by C[icely] V[eronica] Wedgwood" ],
  "medium" : [ {
    "id" : "http://rdaregistry.info/termList/RDAproductionMethod/1010",
    "label" : "Print"
  } ],
  "title" : "The Common man in the great Civil War",
  "hbzId" : "HT010662586",
  "publication" : [ {
    "type" : [ "PublicationEvent" ],
    "publishedBy" : "Leicester Univ. Pr.",
    "startDate" : "1957"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT010662586",
    "label" : "Culturegraph Ressource"
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/HT010662586",
    "type" : [ "BibliographicDescription" ],
    "dateCreated" : "19990818",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "2023-04-16T01:04:38",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/HT010662586",
        "type" : [ "DataFeedItem" ],
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "label" : "hbz-Ressource HT010662586 im Exportformat MAB2-XML"
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-605#!",
      "label" : "lobid Organisation"
    },
    "label" : "Webseite der hbz-Ressource HT010662586"
  },
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/HT010662586#!"
}
