=== hbz/lobid-resources/src/test/resources/schemas/resource.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "lobid-resources",
  "description": "This is a generic JSON schema for validating a JSON document against the lobid-resources data model",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "@context": {
      "$ref": "context.json"
    },
    "id": {
      "$ref": "id.json"
    },
    "type": {
      "$ref": "type.json"
    },
    "abstract": {
      "title": "Abstract",
      "type": "array"
    },
    "accessRights": {
      "$ref": "accessRights.json"
    },
    "almaMmsId": {
      "title": "ALMA MMS identifier",
      "type": "string",
      "pattern": "\\d{17}"
    },
    "alternateGraphicRepresentation": {
      "$ref": "alternateGraphicRepresentation.json"
    },
    "alternativeTitle": {
      "title": "Variations of the title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b3KatId": {
      "title": "B3Kat identifier",
      "type": "string"
    },
    "bibliographicCitation": {
      "type": "string"
    },
    "bibliographicLevel": {
      "$ref": "bibliographicLevel.json"
    },
    "conditionsOfAccess": {
      "$ref": "conditionsOfAccess.json"
    },
    "containedIn": {
      "$ref": "containedIn.json"
    },
    "containsExampleOfWork": {
      "$ref": "containsExampleOfWork.json"
    },
    "contribution": {
      "$ref": "contribution.json"
    },
    "describedBy": {
      "$ref": "describedBy.json"
    },
    "deprecatedUri": {
      "$ref": "id.json"
    },
    "description": {
      "$ref": "description.json"
    },
    "disambiguatingDescription": {
      "title": "Dynamic helper element for deduplicating efforts.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dnbId": {
      "title": "DNB identifier",
      "type": "string"
    },
    "doi": {
      "$ref": "doi.json"
    },
    "edition": {
      "title": "Statement on the edition of the resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exampleOfWork": {
      "$ref": "exampleOfWork.json"
    },
    "extent": {
      "title": "Extent",
      "type": "string"
    },
    "fulltextOnline": {
      "$ref": "fulltextOnline.json"
    },
    "hasItem": {
      "$ref": "hasItem.json"
    },
    "hbzId": {
      "title": "hbz identifier",
      "type": "string"
    },
    "hebisId": {
      "title": "hebis PPN identifier",
      "type": "string"
    },
    "inCollection": {
      "$ref": "inCollection.json"
    },
    "isPartOf": {
      "$ref": "isPartOf.json"
    },
    "isbn": {
      "$ref": "isbn.json"
    },
    "issn": {
      "$ref": "issn.json"
    },
    "ismn": {
      "$ref": "ismn.json"
    },
    "k10PlusId": {
      "title": "K10Plus identifier",
      "type": "string"
    },
    "langNote": {
      "title": "Note concerning the language of a resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "language": {
      "$ref": "language.json"
    },
    "license": {
      "$ref": "license.json"
    },
    "manufacture": {
      "$ref": "manufacture.json"
    },
    "medium": {
      "$ref": "medium.json"
    },
    "natureOfContent": {
      "$ref": "natureOfContent.json"
    },
    "note": {
      "$ref": "note.json"
    },
    "oclcNumber": {
      "title": "OCLC number",
      "description": "The OCLC number of the resource",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "\\d{1,14}"
      }
    },
    "otherTitleInformation": {
      "title": "Additional title information",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "predecessor": {
      "$ref": "predecessor.json"
    },
    "primaryForm": {
      "$ref": "primaryForm.json"
    },
    "publication": {
      "$ref": "publication.json"
    },
    "related": {
      "$ref": "related.json"
    },
    "responsibilityStatement": {
      "title": "Responsibility Statement",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rpbId": {
      "title": "RPB identifier",
      "type": "string"
    },
    "sameAs": {
      "$ref": "sameAs.json"
    },
    "secondaryForm": {
      "$ref": "secondaryForm.json"
    },
    "seeAlso": {
      "$ref": "seeAlso.json"
    },
    "shortTitle": {
      "title": "Short version of title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "spatial": {
      "$ref": "spatial.json"
    },
    "stockNumber": {
      "title": "Product identifier from retail or publisher",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subject": {
      "title": "Subject",
      "description": "Subject indexing of the resource",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "complexSubject.json"
          },
          {
            "$ref": "skosConcept.json"
          }
        ]
      }
    },
    "subjectAltLabel": {
      "title": "Alternative labels for subjects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subjectslabels": {
      "title": "Labels for all subjects needed by Digibib",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "successor": {
      "$ref": "successor.json"
    },
    "supplement": {
      "$ref": "supplement.json"
    },
    "tableOfContents": {
      "$ref": "tableOfContents.json"
    },
    "thesisInformation": {
      "title": "Information specific to the doctoral thesis",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "title": {
      "title": "Title",
      "type": "string"
    },
    "titleKeyword": {
      "title": "Keywords taken from the title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "urn": {
      "title": "urn",
      "description": "urn of the resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "webPageArchived": {
      "$ref": "webPageArchived.json"
    },
    "zdbId": {
      "title": "ZDB identifier",
      "type": "string",
      "pattern": "\\d{1,7}-[Xx\\d]"
    }
  },
  "required": [
    "@context",
    "id",
    "type"
  ]
}

=== hbz/lobid-resources/src/test/resources/alma-fix/990366624790206441.json
{
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/990366624790206441#!",
  "type" : [ "BibliographicResource", "Book" ],
  "medium" : [ {
    "label" : "Datenträger",
    "id" : "http://rdaregistry.info/termList/RDAMediaType/1003"
  }, {
    "label" : "Online-Ressource",
    "id" : "http://rdaregistry.info/termList/RDACarrierType/1018"
  } ],
  "title" : "Der Anti-Bias-Ansatz",
  "almaMmsId" : "990366624790206441",
  "hbzId" : "HT020469610",
  "deprecatedUri" : "http://lobid.org/resources/HT020469610#!",
  "isbn" : [ "9783531922089", "3531922084" ],
  "otherTitleInformation" : [ "Zu Konzept und Praxis einer Pädagogik für den Umgang mit (kultureller) Vielfalt" ],
  "publication" : [ {
    "startDate" : "2010",
    "type" : [ "PublicationEvent" ],
    "location" : [ "Wiesbaden" ],
    "publishedBy" : [ "VS Verlag fur Sozialwissenschaften GmbH" ]
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/990366624790206441",
    "label" : "Webseite der hbz-Ressource 990366624790206441",
    "type" : [ "BibliographicDescription" ],
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "0000-00-00T00:00:00",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "https://lobid.org/marcxml/990366624790206441",
        "dateCreated" : "2021-04-06",
        "dateModified" : "2022-11-09",
        "type" : [ "DataFeedItem" ],
        "label" : "hbz-Ressource 990366624790206441 im Exportformat MARC21 XML",
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "sourceOrganization" : {
          "id" : "http://lobid.org/organisations/DE-Hag4#!",
          "label" : "Fachhochschule Südwestfalen, Fachbibliothek Hagen, Zentralbibliothek"
        },
        "provider" : {
          "id" : "http://lobid.org/organisations/DE-605#!",
          "label" : "hbz - Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen"
        },
        "modifiedBy" : [ {
          "id" : "http://lobid.org/organisations/DE-575#!",
          "label" : "Hochschule für Musik Detmold, Bibliothek"
        }, {
          "id" : "http://lobid.org/organisations/DE-605#!",
          "label" : "hbz - Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen"
        } ]
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ]
  },
  "sameAs" : [ {
    "id" : "https://hub.culturegraph.org/resource/(DE-605)990366624790206441",
    "label" : "Culturegraph Ressource"
  } ],
  "related" : [ {
    "note" : [ "Druck-Ausgabe" ],
    "isbn" : [ "9783531171333", "353117133X" ]
  } ],
  "inCollection" : [ {
    "id" : "http://lobid.org/organisations/DE-655#!",
    "label" : "hbz - Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen, Netzwerkzone",
    "type" : [ "Collection" ]
  }, {
    "id" : "http://lobid.org/organisations/ZDB-30-PQE#!",
    "label" : "ProQuest Ebook Central",
    "type" : [ "Collection" ]
  } ],
  "language" : [ {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/ger",
    "label" : "Deutsch"
  } ],
  "extent" : "1 Online-Ressource (230 Seiten)",
  "hasItem" : [ {
    "type" : [ "Item", "DigitalDocument" ],
    "label" : "Electronic Portfolio",
    "electronicLocator" : "https://eu04.alma.exlibrisgroup.com/view/uresolver/49HBZ_FSW/openurl?u.ignore_date_coverage=true&portfolio_pid=5378132900006461&Force_direct=true",
    "sublocation" : "https://hbz-network.userservices.exlibrisgroup.com/view/uresolver/49HBZ_FSW/openurl?u.ignore_date_coverage=true&rft.mms_id=990012937280106461",
    "heldBy" : {
      "isil" : "DE-Hag4",
      "id" : "http://lobid.org/organisations/DE-Hag4#!",
      "label" : "Fachhochschule Südwestfalen, Fachbibliothek Hagen, Zentralbibliothek"
    },
    "seeAlso" : [ "https://kai.fh-swf.de/permalink/49HBZ_FSW/ou32r9/alma990366624790206441" ],
    "inCollection" : [ {
      "id" : "http://lobid.org/organisations/DE-Hag4#!",
      "label" : "Fachhochschule Südwestfalen, Fachbibliothek Hagen, Zentralbibliothek"
    } ],
    "id" : "http://lobid.org/items/990366624790206441:DE-Hag4:5378132900006461#!"
  }, {
    "type" : [ "Item", "DigitalDocument" ],
    "label" : "Electronic Portfolio",
    "electronicLocator" : "https://eu04.alma.exlibrisgroup.com/view/uresolver/49HBZ_DET/openurl?u.ignore_date_coverage=true&portfolio_pid=53102917670006480&Force_direct=true",
    "sublocation" : "https://hbz-network.userservices.exlibrisgroup.com/view/uresolver/49HBZ_DET/openurl?u.ignore_date_coverage=true&rft.mms_id=991006843529706480",
    "heldBy" : {
      "isil" : "DE-575",
      "id" : "http://lobid.org/organisations/DE-575#!",
      "label" : "Hochschule für Musik Detmold, Bibliothek"
    },
    "seeAlso" : [ "https://det.digibib.net/search/katalog/record/(DE-605)HT020469610" ],
    "inCollection" : [ {
      "id" : "http://lobid.org/organisations/DE-51#!",
      "label" : "Lippische Landesbibliothek - Theologische Bibliothek und Mediothek"
    } ],
    "id" : "http://lobid.org/items/990366624790206441:DE-575:53102917670006480#!"
  } ],
  "bibliographicLevel" : {
    "label" : "Monograph/Item",
    "id" : "https://www.loc.gov/marc/bibliographic/bdleader.html#Monograph_Item"
  },
  "responsibilityStatement" : [ "Katja Gramelt" ],
  "contribution" : [ {
    "agent" : {
      "gndIdentifier" : "140303286",
      "id" : "https://d-nb.info/gnd/140303286",
      "label" : "Gramelt, Katja",
      "type" : [ "Person" ]
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    },
    "type" : [ "Contribution" ]
  } ]
}

=== hbz/lobid-resources/src/test/resources/alma/(DE-605)HT020297152.json
{
  "@context" : "http://lobid.org/resources/context.jsonld",
  "almaMmsId" : "990364897030206441",
  "hbzId" : "HT020297152",
  "title" : "Die Erfindung des Rockkonzerts in der Provinz",
  "otherTitleInformation" : [ "ein praxeologischer Blick auf das Soester \"Karussell der Jugend\" 1959-1971" ],
  "responsibilityStatement" : [ "Peter Klose" ],
  "publication" : [ {
    "publicationHistory" : "2019",
    "startDate" : "2019",
    "type" : [ "PublicationEvent" ]
  } ],
  "hasItem" : [ {
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-605#!",
      "label" : "lobid Organisation"
    },
    "id" : "https://lobid.org/item/990364897030206441",
    "type" : [ "MBD" ],
    "label" : "990364897030206441"
  } ],
  "type" : [ "Book", "BibliographicResource" ],
  "language" : [ {
    "label" : "Deutsch",
    "id" : "http://id.loc.gov/vocabulary/iso639-2/ger"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT020297152",
    "label" : "Culturegraph Ressource"
  } ],
  "extent" : "Illustrationen, Diagramm",
  "isPartOf" : [ {
    "type" : "IsPartOfRelation",
    "hasSuperordinate" : [ {
      "label" : "(Dis-)Orienting Sounds / Ralf von Appen, Mario Dunkel (Hg.)",
      "id" : "http://lobid.org/resources/HT020255346#!"
    } ]
  } ],
  "inCollection" : [ {
    "label" : "Nordrhein-Westfälische Bibliographie (NWBib)",
    "id" : "http://lobid.org/resources/HT014176012#!",
    "type" : [ "Collection" ]
  }, {
    "id" : "https://lobid.org/collections#NWBib-6",
    "type" : [ "Collection" ],
    "label" : "collections#NWBib-6"
  } ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "label" : "Klose, Peter",
      "type" : [ "Person" ],
      "gndIdentifier" : "135325900",
      "id" : "https://d-nb.info/gnd/135325900"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    }
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/990364897030206441",
    "label" : "Webseite der hbz-Ressource 990364897030206441",
    "type" : [ "BibliographicDescription" ],
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-6#!",
      "label" : "lobid Organisation"
    },
    "dateModified" : "20210409",
    "dateCreated" : "20210405",
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/990364897030206441",
        "type" : [ "DataFeedItem" ],
        "label" : "hbz-Ressource 990364897030206441 im Exportformat MARC21 XML",
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        }
      },
      "endTime" : "dummy"
    }
  },
  "subject" : [ {
    "type" : [ "ComplexSubject" ],
    "label" : "Karussell der Jugend | Geschichte 1959-1971",
    "componentList" : [ {
      "label" : "Karussell der Jugend",
      "type" : [ "ConferenceOrEvent" ],
      "id" : "http://d-nb.info/gnd/1200563662",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "1200563662"
    }, {
      "label" : "Geschichte 1959-1971"
    } ]
  }, {
    "type" : [ "ComplexSubject" ],
    "label" : "Allerheiligenkirmes | Jugend | Tanzveranstaltung | Geschichte 1959-1971",
    "componentList" : [ {
      "label" : "Allerheiligenkirmes",
      "type" : [ "ConferenceOrEvent" ],
      "id" : "http://d-nb.info/gnd/7677592-6",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "7677592-6"
    }, {
      "label" : "Jugend",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4028859-6",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4028859-6"
    }, {
      "label" : "Tanzveranstaltung",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4184453-1",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4184453-1"
    }, {
      "label" : "Geschichte 1959-1971"
    } ]
  } ],
  "subjectAltLabel" : [ "Tanz", "Jugend", "12-20 Jahre", "Jugendalter", "Jugendlicher", "Teenager" ],
  "id" : "http://lobid.org/resources/990364897030206441#!"
}

=== hbz/lobid-resources/src/test/resources/alma/(DE-605)HT014997977.json
{
  "@context" : "http://lobid.org/resources/context.jsonld",
  "almaMmsId" : "990155895060206441",
  "hbzId" : "HT014997977",
  "title" : "Leitfaden für die Behandlung von Ausbauasphalt und Straßenaufbruch mit teer-/pechtypischen Bestandteilen",
  "otherTitleInformation" : [ "Leitfaden für den Geschäftsbereich des Landesbetriebes Straßen und Verkehr" ],
  "responsibilityStatement" : [ "Arbeitskreis Straßenbauabfälle Rheinland-Pfalz; Landesamt für Umweltschutz und Gewerbeaufsicht; Landesbetrieb Straßen und Verkehr Rheinland-Pfalz" ],
  "edition" : [ "1. Aufl." ],
  "publication" : [ {
    "location" : "[Mainz]",
    "publicationHistory" : "2003",
    "startDate" : "2003",
    "type" : [ "PublicationEvent" ]
  } ],
  "hasItem" : [ {
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-605#!",
      "label" : "lobid Organisation"
    },
    "id" : "https://lobid.org/item/990155895060206441",
    "type" : [ "MBD" ],
    "label" : "990155895060206441"
  } ],
  "medium" : [ {
    "id" : "http://rdaregistry.info/termList/RDAMediaType/1003",
    "label" : "Datenträger"
  }, {
    "id" : "http://rdaregistry.info/termList/RDACarrierType/1018",
    "label" : "Online-Ressource"
  } ],
  "type" : [ "Book", "BibliographicResource" ],
  "language" : [ {
    "label" : "Deutsch",
    "id" : "http://id.loc.gov/vocabulary/iso639-2/ger"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT014997977",
    "label" : "Culturegraph Ressource"
  } ],
  "extent" : "15, [14] S. : graph. Darst.",
  "inCollection" : [ {
    "id" : "https://lobid.org/collections#929: edoweb",
    "type" : [ "Collection" ],
    "label" : "collections#929: edoweb"
  } ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "type" : [ "CorporateBody" ],
      "gndIdentifier" : "3062366-2",
      "id" : "https://d-nb.info/gnd/3062366-2",
      "label" : "Arbeitskreis Straßenbauabfälle Rheinland-Pfalz"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/oth",
      "label" : "Sonstige"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "type" : [ "CorporateBody" ],
      "gndIdentifier" : "10048424-4",
      "id" : "https://d-nb.info/gnd/10048424-4",
      "label" : "Landesbetrieb Straßen und Verkehr Rheinland-Pfalz"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/oth",
      "label" : "Sonstige"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "type" : [ "CorporateBody" ],
      "gndIdentifier" : "2092393-4",
      "id" : "https://d-nb.info/gnd/2092393-4",
      "label" : "Rheinland-Pfalz. Landesamt für Umweltschutz und Gewerbeaufsicht"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/oth",
      "label" : "Sonstige"
    }
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/990155895060206441",
    "label" : "Webseite der hbz-Ressource 990155895060206441",
    "type" : [ "BibliographicDescription" ],
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-929#!",
      "label" : "lobid Organisation"
    },
    "dateModified" : "20210408",
    "dateCreated" : "20210406",
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/990155895060206441",
        "type" : [ "DataFeedItem" ],
        "label" : "hbz-Ressource 990155895060206441 im Exportformat MARC21 XML",
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        }
      },
      "endTime" : "dummy"
    }
  },
  "subject" : [ {
    "notation" : "380",
    "label" : "Handel, Kommunikation, Verkehr",
    "source" : {
      "id" : "http://d-nb.info/gnd/4149423-4",
      "label" : "Dewey-Dezimalklassifikation"
    }
  } ],
  "id" : "http://lobid.org/resources/990155895060206441#!"
}

=== hbz/lobid-resources/src/test/resources/jsonld/HT008359420.json
{
  "type" : [ "BibliographicResource", "Book" ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/119057603",
      "type" : [ "Person" ],
      "label" : "Steck, Odil Hannes",
      "altLabel" : [ "Steck, Odil", "Steck, O. H.", "Steck, Odil H." ],
      "dateOfBirth" : "1935",
      "dateOfDeath" : "2001",
      "gndIdentifier" : "119057603"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    }
  } ],
  "extent" : "83 S.",
  "responsibilityStatement" : [ "Odil Hannes Steck" ],
  "language" : [ {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/deu",
    "label" : "Deutsch"
  } ],
  "medium" : [ {
    "id" : "http://purl.org/lobid/lv#Miscellaneous",
    "label" : "Sonstige"
  } ],
  "subject" : [ {
    "type" : [ "ComplexSubject" ],
    "componentList" : [ {
      "id" : "https://d-nb.info/gnd/4028593-5",
      "type" : [ "Work" ],
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "label" : "Bibel. Jesaja",
      "gndIdentifier" : "4028593-5"
    }, {
      "id" : "https://d-nb.info/gnd/4049716-1",
      "type" : [ "SubjectHeading" ],
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "label" : "Rezeption",
      "gndIdentifier" : "4049716-1"
    }, {
      "id" : "https://d-nb.info/gnd/4539193-2",
      "type" : [ "Work" ],
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "label" : "Jesajarolle, Qumrantexte",
      "gndIdentifier" : "4539193-2"
    } ],
    "label" : "Bibel. Jesaja | Rezeption | Qumrantexte: Jesajarolle"
  }, {
    "type" : [ "ComplexSubject" ],
    "componentList" : [ {
      "id" : "https://d-nb.info/gnd/4539193-2",
      "type" : [ "Work" ],
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "label" : "Jesajarolle, Qumrantexte",
      "gndIdentifier" : "4539193-2"
    }, {
      "type" : [ "SubjectHeading" ],
      "label" : "Quelle"
    } ],
    "label" : "Qumrantexte: Jesajarolle | Quelle"
  } ],
  "title" : "Die erste Jesajarolle von Qumran (1QIs a), 2: Textheft",
  "hbzId" : "HT008359420",
  "isPartOf" : [ {
    "type" : [ "IsPartOfRelation" ],
    "hasSuperordinate" : [ {
      "id" : "http://lobid.org/resources/HT008359395#!",
      "label" : "lobid Ressource"
    } ],
    "numbering" : "2"
  } ],
  "subjectAltLabel" : [ "Jerusalem / 1QIsª", "Fortwirken", "Aneignung (Rezeption)", "Nachwirkung (Rezeption)", "Nachleben", "Wirkungsgeschichte" ],
  "publication" : [ {
    "type" : [ "PublicationEvent" ],
    "location" : "Stuttgart",
    "publishedBy" : "Verl. Kath. Bibelwerk",
    "startDate" : "1998"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT008359420",
    "label" : "Culturegraph Ressource"
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/HT008359420",
    "type" : [ "BibliographicDescription" ],
    "dateCreated" : "19980422",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "0001-01-01T00:00:00",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/HT008359420",
        "type" : [ "DataFeedItem" ],
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "label" : "hbz-Ressource HT008359420 im Exportformat MAB2-XML"
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-292#!",
      "label" : "lobid Organisation"
    },
    "label" : "Webseite der hbz-Ressource HT008359420"
  },
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/HT008359420#!"
}
