=== hbz/lobid-resources/src/test/resources/schemas/resource.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "lobid-resources",
  "description": "This is a generic JSON schema for validating a JSON document against the lobid-resources data model",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "@context": {
      "$ref": "context.json"
    },
    "id": {
      "$ref": "id.json"
    },
    "type": {
      "$ref": "type.json"
    },
    "abstract": {
      "title": "Abstract",
      "type": "array"
    },
    "accessRights": {
      "$ref": "accessRights.json"
    },
    "almaMmsId": {
      "title": "ALMA MMS identifier",
      "type": "string",
      "pattern": "\\d{17}"
    },
    "alternateGraphicRepresentation": {
      "$ref": "alternateGraphicRepresentation.json"
    },
    "alternativeTitle": {
      "title": "Variations of the title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "b3KatId": {
      "title": "B3Kat identifier",
      "type": "string"
    },
    "bibliographicCitation": {
      "type": "string"
    },
    "bibliographicLevel": {
      "$ref": "bibliographicLevel.json"
    },
    "conditionsOfAccess": {
      "$ref": "conditionsOfAccess.json"
    },
    "containedIn": {
      "$ref": "containedIn.json"
    },
    "containsExampleOfWork": {
      "$ref": "containsExampleOfWork.json"
    },
    "contribution": {
      "$ref": "contribution.json"
    },
    "describedBy": {
      "$ref": "describedBy.json"
    },
    "deprecatedUri": {
      "$ref": "id.json"
    },
    "description": {
      "$ref": "description.json"
    },
    "disambiguatingDescription": {
      "title": "Dynamic helper element for deduplicating efforts.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dnbId": {
      "title": "DNB identifier",
      "type": "string"
    },
    "doi": {
      "$ref": "doi.json"
    },
    "edition": {
      "title": "Statement on the edition of the resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exampleOfWork": {
      "$ref": "exampleOfWork.json"
    },
    "extent": {
      "title": "Extent",
      "type": "string"
    },
    "fulltextOnline": {
      "$ref": "fulltextOnline.json"
    },
    "hasItem": {
      "$ref": "hasItem.json"
    },
    "hbzId": {
      "title": "hbz identifier",
      "type": "string"
    },
    "hebisId": {
      "title": "hebis PPN identifier",
      "type": "string"
    },
    "inCollection": {
      "$ref": "inCollection.json"
    },
    "isPartOf": {
      "$ref": "isPartOf.json"
    },
    "isbn": {
      "$ref": "isbn.json"
    },
    "issn": {
      "$ref": "issn.json"
    },
    "ismn": {
      "$ref": "ismn.json"
    },
    "k10PlusId": {
      "title": "K10Plus identifier",
      "type": "string"
    },
    "langNote": {
      "title": "Note concerning the language of a resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "language": {
      "$ref": "language.json"
    },
    "license": {
      "$ref": "license.json"
    },
    "manufacture": {
      "$ref": "manufacture.json"
    },
    "medium": {
      "$ref": "medium.json"
    },
    "natureOfContent": {
      "$ref": "natureOfContent.json"
    },
    "note": {
      "$ref": "note.json"
    },
    "oclcNumber": {
      "title": "OCLC number",
      "description": "The OCLC number of the resource",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "\\d{1,14}"
      }
    },
    "otherTitleInformation": {
      "title": "Additional title information",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "predecessor": {
      "$ref": "predecessor.json"
    },
    "primaryForm": {
      "$ref": "primaryForm.json"
    },
    "publication": {
      "$ref": "publication.json"
    },
    "related": {
      "$ref": "related.json"
    },
    "responsibilityStatement": {
      "title": "Responsibility Statement",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rpbId": {
      "title": "RPB identifier",
      "type": "string"
    },
    "sameAs": {
      "$ref": "sameAs.json"
    },
    "secondaryForm": {
      "$ref": "secondaryForm.json"
    },
    "seeAlso": {
      "$ref": "seeAlso.json"
    },
    "shortTitle": {
      "title": "Short version of title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "spatial": {
      "$ref": "spatial.json"
    },
    "stockNumber": {
      "title": "Product identifier from retail or publisher",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subject": {
      "title": "Subject",
      "description": "Subject indexing of the resource",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "complexSubject.json"
          },
          {
            "$ref": "skosConcept.json"
          }
        ]
      }
    },
    "subjectAltLabel": {
      "title": "Alternative labels for subjects",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subjectslabels": {
      "title": "Labels for all subjects needed by Digibib",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "successor": {
      "$ref": "successor.json"
    },
    "supplement": {
      "$ref": "supplement.json"
    },
    "tableOfContents": {
      "$ref": "tableOfContents.json"
    },
    "thesisInformation": {
      "title": "Information specific to the doctoral thesis",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "title": {
      "title": "Title",
      "type": "string"
    },
    "titleKeyword": {
      "title": "Keywords taken from the title",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "urn": {
      "title": "urn",
      "description": "urn of the resource",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "webPageArchived": {
      "$ref": "webPageArchived.json"
    },
    "zdbId": {
      "title": "ZDB identifier",
      "type": "string",
      "pattern": "\\d{1,7}-[Xx\\d]"
    }
  },
  "required": [
    "@context",
    "id",
    "type"
  ]
}

=== hbz/lobid-resources/src/test/resources/timeCapsuleAlephData/HT019093814_aleph.json
{
  "type" : [ "Book", "BibliographicResource" ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/1108328849",
      "type" : [ "Person" ],
      "label" : "Boeszoermeny, Louisa",
      "dateOfBirth" : "1991",
      "gndIdentifier" : "1108328849"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/pht",
      "label" : "Fotografie"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/1067217789",
      "type" : [ "Person" ],
      "label" : "Ganslmeier, Jakob",
      "dateOfBirth" : "1990",
      "gndIdentifier" : "1067217789"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/pht",
      "label" : "Fotografie"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/10057549-3",
      "type" : [ "CorporateBody" ],
      "label" : "Kultur Ruhr GmbH",
      "gndIdentifier" : "10057549-3"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ctb",
      "label" : "Beitragende/r"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "id" : "https://d-nb.info/gnd/5555595-0",
      "type" : [ "ConferenceOrEvent" ],
      "label" : "Ruhrtriennale",
      "altLabel" : "Ruhr-Triennale",
      "gndIdentifier" : "5555595-0"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/ctb",
      "label" : "Beitragende/r"
    }
  } ],
  "extent" : "[110] S. : zahlr. Ill., überw. farb.",
  "hasItem" : [ {
    "id" : "http://lobid.org/items/HT019093814:DE-Kn3:KMB%2FYF%20DEUTSC%20%202016%20A#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-Kn3#!",
      "label" : "lobid Organisation"
    },
    "note" : [ "00020050" ],
    "callNumber" : "KMB/YF DEUTSC  2016 A",
    "label" : "KMB/YF DEUTSC  2016 A"
  }, {
    "id" : "http://lobid.org/items/HT019093814:DE-465:JZH43391#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-465#!",
      "label" : "lobid Organisation"
    },
    "note" : [ "E11" ],
    "callNumber" : "JZH43391",
    "label" : "JZH43391"
  }, {
    "id" : "http://lobid.org/items/HT019093814:DE-Bm3-3:A%2012%20647#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-Bm3-3#!",
      "label" : "lobid Organisation"
    },
    "note" : [ "K02" ],
    "callNumber" : "A 12 647",
    "label" : "A 12 647"
  }, {
    "id" : "http://lobid.org/items/HT019093814:DE-6:LC%201017#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-6#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "LC 1017",
    "label" : "LC 1017"
  } ],
  "note" : [ "Wendebuch" ],
  "alternativeTitle" : [ "Licht unserer Tage", "Bude Bett Bargeld" ],
  "language" : [ {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/deu",
    "label" : "Deutsch"
  }, {
    "id" : "http://id.loc.gov/vocabulary/iso639-2/eng",
    "label" : "Englisch"
  } ],
  "medium" : [ {
    "id" : "http://rdaregistry.info/termList/RDAproductionMethod/1010",
    "label" : "Print"
  } ],
  "spatial" : [ {
    "id" : "https://nwbib.de/spatial#N20",
    "type" : [ "Concept" ],
    "source" : {
      "id" : "https://nwbib.de/spatial",
      "label" : "Raumsystematik der Nordrhein-Westfälischen Bibliographie"
    },
    "label" : "Ruhrgebiet",
    "notation" : "20",
    "focus" : {
      "id" : "http://www.wikidata.org/entity/Q151993",
      "type" : [ "http://www.wikidata.org/entity/Q245260" ],
      "geo" : {
        "lat" : "51.5",
        "lon" : "7.5"
      },
      "label" : "Ruhrgebiet"
    }
  } ],
  "subject" : [ {
    "type" : [ "ComplexSubject" ],
    "componentList" : [ {
      "id" : "https://d-nb.info/gnd/1063656419",
      "type" : [ "ConferenceOrEvent" ],
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "label" : "Ruhrtriennale (2015-2017 : Nordrhein-Westfalen)",
      "gndIdentifier" : "1063656419"
    }, {
      "id" : "https://d-nb.info/gnd/4045895-7",
      "type" : [ "SubjectHeading" ],
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "label" : "Fotografie",
      "gndIdentifier" : "4045895-7"
    } ],
    "label" : "Ruhrtriennale (2015-2017), Nordrhein-Westfalen | Fotografie"
  }, {
    "id" : "https://nwbib.de/subjects#N848000",
    "source" : {
      "id" : "https://nwbib.de/subjects",
      "label" : "Sachsystematik der Nordrhein-Westfälischen Bibliographie"
    },
    "notation" : "848000",
    "label" : "Photographie"
  }, {
    "id" : "https://nwbib.de/subjects#N841060",
    "source" : {
      "id" : "https://nwbib.de/subjects",
      "label" : "Sachsystematik der Nordrhein-Westfälischen Bibliographie"
    },
    "notation" : "841060",
    "label" : "Kunstausstellungen"
  } ],
  "title" : "Bude Bett Bargeld / Licht unserer Tage",
  "hbzId" : "HT019093814",
  "inCollection" : [ {
    "id" : "http://lobid.org/resources/HT014176012#!",
    "type" : [ "Collection" ],
    "label" : "Nordrhein-Westfälische Bibliographie (NWBib)"
  } ],
  "subjectAltLabel" : [ "Lichtbild (Fotographie)", "Lichtbild (Photographie)", "Photographieren", "Photografie", "Nordrhein-Westfalen (Nordrhein-Westfalen)", "Fotografische Aufnahme", "Foto", "Lichtbild (Photografie)", "Fotoaufnahme", "Aufnahme (Fotografie)", "Photo", "Fotografieren", "Aufnahme (Photografie)", "Fotographie", "Lichtbild (Fotografie)", "Photografieren", "Photoaufnahme", "Photografische Aufnahme", "Photographische Aufnahme", "Photokunst", "Fotographieren", "Fotokunst", "Aufnahme (Photographie)", "Photographie", "Aufnahme (Fotographie)", "Fotographische Aufnahme" ],
  "edition" : [ "[1. Auflage]" ],
  "isbn" : [ "9783954761586" ],
  "oclcNumber" : [ "1076073898" ],
  "otherTitleInformation" : [ "junge Fotografie, Ruhrtriennale 2016 : Meisterkurse Daniel Josefson und Julian Römer; Louisa Boeszoermeny, Jakob Ganslmeier, Gregro Schmidt, Julian Slagman" ],
  "natureOfContent" : [ {
    "id" : "https://d-nb.info/gnd/1071861417",
    "label" : "Konferenzschrift"
  } ],
  "publication" : [ {
    "type" : [ "PublicationEvent" ],
    "location" : "Berlin",
    "publishedBy" : "Distanz",
    "startDate" : "2016"
  } ],
  "sameAs" : [ {
    "id" : "http://worldcat.org/oclc/1076073898",
    "label" : "1076073898"
  }, {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT019093814",
    "label" : "Culturegraph Ressource"
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/HT019093814",
    "type" : [ "BibliographicDescription" ],
    "modifiedBy" : {
      "id" : "http://lobid.org/organisations/DE-Kn3#!",
      "label" : "lobid Organisation"
    },
    "dateCreated" : "20160915",
    "dateModified" : "20210409",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "2023-04-16T02:40:19",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/HT019093814",
        "type" : [ "DataFeedItem" ],
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "label" : "hbz-Ressource HT019093814 im Exportformat MAB2-XML"
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-Kn3#!",
      "label" : "lobid Organisation"
    },
    "label" : "Webseite der hbz-Ressource HT019093814"
  },
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/HT019093814#!"
}

=== hbz/lobid-resources/src/test/resources/alma/(DE-605)HT017536715.json
{
  "@context" : "http://lobid.org/resources/context.jsonld",
  "almaMmsId" : "990194515170206441",
  "hbzId" : "HT017536715",
  "title" : "Die Evangelische Kirche im Wandel",
  "otherTitleInformation" : [ "Luthers Erben an der Ruhr" ],
  "responsibilityStatement" : [ "Thomas Emons" ],
  "publication" : [ {
    "publicationHistory" : "2012",
    "startDate" : "2012",
    "type" : [ "PublicationEvent" ]
  } ],
  "hasItem" : [ {
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-605#!",
      "label" : "lobid Organisation"
    },
    "id" : "https://lobid.org/item/990194515170206441",
    "type" : [ "MBD" ],
    "label" : "990194515170206441"
  } ],
  "type" : [ "Book", "BibliographicResource" ],
  "language" : [ {
    "label" : "Deutsch",
    "id" : "http://id.loc.gov/vocabulary/iso639-2/ger"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT017536715",
    "label" : "Culturegraph Ressource"
  } ],
  "isPartOf" : [ {
    "type" : "IsPartOfRelation",
    "hasSuperordinate" : [ {
      "label" : "Jahrbuch / Mülheim an der Ruhr",
      "id" : "http://lobid.org/resources/HT006816401#!"
    } ]
  } ],
  "inCollection" : [ {
    "label" : "Nordrhein-Westfälische Bibliographie (NWBib)",
    "id" : "http://lobid.org/resources/HT014176012#!",
    "type" : [ "Collection" ]
  }, {
    "id" : "https://lobid.org/collections#NWBib-61",
    "type" : [ "Collection" ],
    "label" : "collections#NWBib-61"
  } ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "label" : "Emons, Thomas",
      "type" : [ "Person" ],
      "gndIdentifier" : "129424323",
      "id" : "https://d-nb.info/gnd/129424323"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    }
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/990194515170206441",
    "label" : "Webseite der hbz-Ressource 990194515170206441",
    "type" : [ "BibliographicDescription" ],
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-Bm 3#!",
      "label" : "lobid Organisation"
    },
    "modifiedBy" : {
      "id" : "http://lobid.org/organisations/DE-61#!",
      "label" : "lobid Organisation"
    },
    "dateModified" : "20210731",
    "dateCreated" : "20210405",
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/990194515170206441",
        "type" : [ "DataFeedItem" ],
        "label" : "hbz-Ressource 990194515170206441 im Exportformat MARC21 XML",
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        }
      },
      "endTime" : "dummy"
    }
  },
  "subject" : [ {
    "type" : [ "ComplexSubject" ],
    "label" : "Mülheim an der Ruhr | Evangelische Kirche im Rheinland | Geschichte",
    "componentList" : [ {
      "label" : "Mülheim an der Ruhr",
      "type" : [ "PlaceOrGeographicName" ],
      "id" : "http://d-nb.info/gnd/4040475-4",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4040475-4"
    }, {
      "label" : "Evangelische Kirche im Rheinland",
      "type" : [ "CorporateBody" ],
      "id" : "http://d-nb.info/gnd/1183319010",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "1183319010"
    }, {
      "label" : "Geschichte"
    } ]
  } ],
  "subjectAltLabel" : [ "Mülheim, Ruhr", "Mülheim", "Mülheim a. d. Ruhr" ],
  "id" : "http://lobid.org/resources/990194515170206441#!"
}

=== hbz/lobid-resources/src/test/resources/timeCapsuleAlephData/TT000136775_aleph.json
{
  "type" : [ "Book", "BibliographicResource" ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "type" : [ "Person" ],
      "label" : "Waltershausen, Hermann W. von"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    }
  } ],
  "extent" : "81 S.",
  "hasItem" : [ {
    "id" : "http://lobid.org/items/TT000136775:DE-1156:Sbh%2070%20%2F%20Wal#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-1156#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "Sbh 70 / Wal",
    "label" : "Sbh 70 / Wal"
  }, {
    "id" : "http://lobid.org/items/TT000136775:DE-1156:Sbh%2070%20%2F%20Wal%20%2F%20a#!",
    "type" : [ "Item" ],
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-1156#!",
      "label" : "lobid Organisation"
    },
    "callNumber" : "Sbh 70 / Wal / a",
    "label" : "Sbh 70 / Wal / a"
  } ],
  "responsibilityStatement" : [ "von Herm. W. v. Waltershausen" ],
  "medium" : [ {
    "id" : "http://rdaregistry.info/termList/RDAproductionMethod/1010",
    "label" : "Print"
  } ],
  "title" : "Dirigenten-Erziehung",
  "hbzId" : "TT000136775",
  "isPartOf" : [ {
    "type" : [ "IsPartOfRelation" ],
    "hasSuperordinate" : [ {
      "id" : "http://lobid.org/resources/TT001211556#!",
      "label" : "Musikpädagogische Bibliothek"
    } ],
    "numbering" : "4"
  } ],
  "publication" : [ {
    "type" : [ "PublicationEvent" ],
    "location" : "Leipzig",
    "publishedBy" : "Quelle & Meyer",
    "startDate" : "1929"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-TT000136775",
    "label" : "Culturegraph Ressource"
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/TT000136775",
    "type" : [ "BibliographicDescription" ],
    "modifiedBy" : {
      "id" : "http://lobid.org/organisations/DE-605#!",
      "label" : "lobid Organisation"
    },
    "dateCreated" : "19980518",
    "dateModified" : "20180122",
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "endTime" : "2023-04-16T04:37:34",
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/TT000136775",
        "type" : [ "DataFeedItem" ],
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        },
        "label" : "hbz-Ressource TT000136775 im Exportformat MAB2-XML"
      }
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "label" : "Webseite der hbz-Ressource TT000136775"
  },
  "@context" : "http://lobid.org/resources/context.jsonld",
  "id" : "http://lobid.org/resources/TT000136775#!"
}

=== hbz/lobid-resources/src/test/resources/alma/(DE-605)HT020163348.json
{
  "@context" : "http://lobid.org/resources/context.jsonld",
  "almaMmsId" : "990363553190206441",
  "hbzId" : "HT020163348",
  "title" : "Der Prozess der Berufsorientierung aus der Perspektive der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen",
  "responsibilityStatement" : [ "vorgelegt von Carina Hübner ; erster Gutachter: Prof. Dr. Rüdiger Kißgen" ],
  "publication" : [ {
    "location" : "Siegen",
    "publicationHistory" : "2019",
    "startDate" : "2019",
    "type" : [ "PublicationEvent" ]
  } ],
  "hasItem" : [ {
    "heldBy" : {
      "id" : "http://lobid.org/organisations/DE-605#!",
      "label" : "lobid Organisation"
    },
    "id" : "https://lobid.org/item/990363553190206441",
    "type" : [ "MBD" ],
    "label" : "990363553190206441"
  } ],
  "type" : [ "Thesis", "Book", "BibliographicResource" ],
  "language" : [ {
    "label" : "Deutsch",
    "id" : "http://id.loc.gov/vocabulary/iso639-2/ger"
  } ],
  "sameAs" : [ {
    "id" : "http://hub.culturegraph.org/resource/HBZ-HT020163348",
    "label" : "Culturegraph Ressource"
  } ],
  "extent" : "272 Seiten : Diagramme, Illustrationen",
  "related" : [ {
    "label" : "Der Prozess der Berufsorientierung aus der Perspektive der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen",
    "id" : "http://lobid.org/resources/HT020163372#!",
    "note" : "Erscheint auch als Online-Ausgabe, PDF"
  } ],
  "inCollection" : [ {
    "label" : "Nordrhein-Westfälische Bibliographie (NWBib)",
    "id" : "http://lobid.org/resources/HT014176012#!",
    "type" : [ "Collection" ]
  }, {
    "id" : "https://lobid.org/collections#NWBib-6",
    "type" : [ "Collection" ],
    "label" : "collections#NWBib-6"
  } ],
  "contribution" : [ {
    "type" : [ "Contribution" ],
    "agent" : {
      "label" : "Hübner, Carina",
      "type" : [ "Person" ],
      "gndIdentifier" : "1153229838",
      "id" : "https://d-nb.info/gnd/1153229838"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/aut",
      "label" : "Autor/in"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "label" : "Kißgen, Rüdiger",
      "type" : [ "Person" ],
      "gndIdentifier" : "122065514",
      "id" : "https://d-nb.info/gnd/122065514"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/dgs",
      "label" : "Akademische Betreuung"
    }
  }, {
    "type" : [ "Contribution" ],
    "agent" : {
      "type" : [ "CorporateBody" ],
      "gndIdentifier" : "64850-4",
      "id" : "https://d-nb.info/gnd/64850-4",
      "label" : "Universität Siegen"
    },
    "role" : {
      "id" : "http://id.loc.gov/vocabulary/relators/dgg",
      "label" : "Grad-verleihende Institution"
    }
  } ],
  "describedBy" : {
    "id" : "http://lobid.org/resources/990363553190206441",
    "label" : "Webseite der hbz-Ressource 990363553190206441",
    "type" : [ "BibliographicDescription" ],
    "inDataset" : {
      "id" : "http://lobid.org/resources/dataset#!",
      "label" : "lobid-resources – Der hbz-Verbundkatalog als Linked Open Data"
    },
    "license" : [ {
      "id" : "http://creativecommons.org/publicdomain/zero/1.0",
      "label" : "Creative Commons-Lizenz CC0 1.0 Universal"
    } ],
    "sourceOrganization" : {
      "id" : "http://lobid.org/organisations/DE-467#!",
      "label" : "lobid Organisation"
    },
    "modifiedBy" : {
      "id" : "http://lobid.org/organisations/DE-6#!",
      "label" : "lobid Organisation"
    },
    "dateModified" : "20210731",
    "dateCreated" : "20210405",
    "resultOf" : {
      "type" : [ "CreateAction" ],
      "instrument" : {
        "id" : "https://github.com/hbz/lobid-resources",
        "type" : [ "SoftwareApplication" ],
        "label" : "Software lobid-resources"
      },
      "object" : {
        "id" : "http://lobid.org/hbz01/990363553190206441",
        "type" : [ "DataFeedItem" ],
        "label" : "hbz-Ressource 990363553190206441 im Exportformat MARC21 XML",
        "inDataset" : {
          "id" : "https://datahub.io/dataset/hbz_unioncatalog",
          "label" : "hbz_unioncatalog"
        }
      },
      "endTime" : "dummy"
    }
  },
  "natureOfContent" : [ {
    "label" : "Hochschulschrift",
    "id" : "http://d-nb.info/gnd/4113937-9"
  } ],
  "subject" : [ {
    "type" : [ "ComplexSubject" ],
    "label" : "Nordrhein-Westfalen | Sonderschule | Berufsorientierung | Lernbehinderter Mensch | Übergang | Arbeitswelt",
    "componentList" : [ {
      "label" : "Nordrhein-Westfalen",
      "type" : [ "PlaceOrGeographicName" ],
      "id" : "http://d-nb.info/gnd/4042570-8",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4042570-8"
    }, {
      "label" : "Sonderschule",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4055542-2",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4055542-2"
    }, {
      "label" : "Berufsorientierung",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4140124-4",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4140124-4"
    }, {
      "label" : "Lernbehinderter Mensch",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4167388-8",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4167388-8"
    }, {
      "label" : "Übergang",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4681060-2",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4681060-2"
    }, {
      "label" : "Arbeitswelt",
      "type" : [ "SubjectHeading" ],
      "id" : "http://d-nb.info/gnd/4002805-7",
      "source" : {
        "id" : "https://d-nb.info/gnd/7749153-1",
        "label" : "Gemeinsame Normdatei (GND)"
      },
      "gndIdentifier" : "4002805-7"
    } ]
  } ],
  "subjectAltLabel" : [ "Arbeitsleben", "Berufsleben", "Lernbehinderter Schüler", "Sonderschüler", "Berufliche Orientierung", "Förderschule", "Sonderschulen", "Förderschulen", "Hilfsschule", "Nord-Westphalie", "Norte-Westfalia", "NRW", "North Rhine-Westphalia", "NW", "Noordrijn-Westfalen", "North-Rhine/Westphalia", "Land Nordrhein-Westfalen", "Universitätsstadt Siegen", "Siegen, Universitätsstadt", "Stadt Siegen", "Sigedunum", "Sigena Nassoviae", "Sigena", "Sigena Nassoviorum" ],
  "id" : "http://lobid.org/resources/990363553190206441#!"
}
